[TASK] added option to add/override record name with attribute proper…
pixelant/pxa_form_enhancement pull request #4
Opened 2017-02-03 12:55 UTC by mesosa

…ty when saving form

2017-02-03 13:16 UTC, phathoang requested changes

2017-02-03 13:16 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +
Remove?

2017-02-03 13:16 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +            $fieldsToProcess = array_map('trim', $fieldsToProcessFromTS);
$fieldsToProcess = GeneralUtility::trimExplode(",", $this->typoScript["fieldsToSaveAsTitle"]); so the previous line isnt needed.

2017-02-03 13:20 UTC, phathoang requested changes

2017-02-03 13:20 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +        $fieldsToProcessFromTS = array();
Strange indentation?

2017-02-03 13:20 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +        if( trim($this->typoScript["fieldsToSaveAsTitle"]) ) {
if (trim($this->typoScript["fieldsToSaveAsTitle"])) {

2017-02-06 08:43 UTC, phathoang requested changes

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +        $fieldsToProcessFromTS = array();
[] instead of array()

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +        $fieldsToProcess = array();
[] instead of array()

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +        $nameFromForm = array();
[] instead of array()

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		if(trim($this->typoScript["fieldsToSaveAsTitle"])) {
Space after if

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		$fieldsToProcess = array();
[] instead of array()

2017-02-06 08:43 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		$nameFromForm = array();
[] instead of array()

2017-02-06 09:01 UTC, phathoang commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +
Remove empty lines?

2017-02-06 09:02 UTC, phathoang approved these changes
👍

2017-02-15 20:28 UTC, MattiasNilsson requested changes

2017-02-15 20:28 UTC, MattiasNilsson commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		if (trim($this->typoScript["fieldsToSaveAsTitle"])) {
Use single quotes instead of double.

2017-02-15 20:28 UTC, MattiasNilsson commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +			$fieldsToProcess = GeneralUtility::trimExplode(",", $this->typoScript["fieldsToSaveAsTitle"]);
Use single quotes instead of double.

2017-02-15 20:28 UTC, MattiasNilsson commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +			$recordTitle .= implode(" ", $nameFromForm) . ' #' . ++$count;
Use single quotes instead of double.

2017-02-15 20:28 UTC, MattiasNilsson commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		if ($recordTitle == '') {
Perform an === absolute comparison.

2017-02-15 20:28 UTC, MattiasNilsson commented on Classes/Form/PostProcess/SaveFormPostProcessorEnhancement.php
> +		if ($recordTitle == '') {
Add space before self::EXT_NAME

2017-04-07 11:19 UTC, MattiasNilsson commented
@anjeylink Should this go into the 2 or 3 release?

2017-04-07 11:56 UTC, anjeylink commented
@MattiasNilsson into 2, this is supported in 3 by default

2017-08-17 07:12 UTC, anjeylink commented
@MattiasNilsson @mesosa i guess we can delete this pull request, because it's not relevant anymore

2017-08-17 07:26 UTC, MattiasNilsson commented
Closed due to old PR.

2017-08-17 07:26 UTC, closed without merging